### ISSUE TITLE
'Module not found' Error 

### ISSUE THREAD

**Issue by maxdietrich** [kristof0425/react-with-breakpoints#19]
When I install this package via npm, it is correctly installed into my node_modules. However, when I try to use it in my code via
```import {ShowAt, HideAt} from 'react-with-breakpoints';```
I get a `Module not found` error. After having a look into the package.json of this module, I saw this line:

https://github.com/kristof0425/react-with-breakpoints/blob/2509e71a1a812e6b72747302da16f6391fadeff9/package.json#L5

This makes npm look inside `node_modules/react-with-breakpoints/dist/withBreakpoint.js`, the dist folder however only contains a `react-with-breakpoints.js`. I believe this is what the `main` Attribute in the `package.json` should point to. Changing this locally resolved the issue for me. As a temporary solution until this is resolved, changing the import statement to
```import { ShowAt, HideAt} from 'react-with-breakpoints/dist/react-with-breakpoints';```
also works.

**Comment by kristof0425** [comment]
You are right, sorry for the inconvenience @maxdietrich! I forgot to update the main attribute in `package.json`. 😞  I'll fix it today.
Thank you for reporting this bug! 🙏

**Comment by kristof0425** [comment]
@maxdietrich Released `v2.0.1`. Please try it out and let me know if you run into an issue. Thanks again for reporting the bug. 🙏 
I'm closing the issue.
