### ISSUE TITLE
currentBreakpoint is not initially set correctly on large screens

### ISSUE THREAD

**Issue by maxdietrich** [kristof0425/react-with-breakpoints#20]
On large screens (with width higher than the large breakpoint), none of the if clauses in `withBreakpoints.handleResize()` is entered. This leaves the `currentBreakpoint` state empty so that `ShowAt` will not show the passed component even when `breakpoint: large` is set. As soon as one resizes the window to be slimmer than the `large` breakpoint, the state is set correctly and it works, this is however not the behavior I would expect.

https://github.com/kristof0425/react-with-breakpoints/blob/2509e71a1a812e6b72747302da16f6391fadeff9/src/withBreakpoints.js#L20-L36

**Comment by kristof0425** [comment]
Hey @maxdietrich  👋 
Can I kindly ask whether you set custom breakpoints?
Btw, I'll look into this today.
Thank you for reporting this! 😃

**Comment by maxdietrich** [comment]
Thank you! I did, I used the following custom breakpoints:
```
{
  small: 600,
  medium: 960,
  large: 1024
}
```

**Comment by kristof0425** [comment]
@maxdietrich I created the fix for this issue. Pls, let me know if you run into any issues!
Thank you for using `react-with-breakpoints`. 🙏
