### ISSUE TITLE
Use debounce on resizing

### ISSUE THREAD

**Issue by joetidee** [kristof0425/react-with-breakpoints#29]
Any plans for introducing debounce on the resize events to prevent lots of re-renders?

**Comment by kristof0425** [comment]
Sorry for the late answer!

Yes, the resize events should be throttled. I'm happy to create PR for it, but your contribution is also welcomed. 🙂

**Comment by Jakobo** [comment]
@joetidee I've got a PR up for the code w/ debouncing the `handleResize()`

Thankfully, in practice, the really-expensive-operation (setState + re-render) is only happening when you cross a breakpoint threshold.
