### ISSUE TITLE
Include xlarge breakpoint

### ISSUE THREAD

**Issue by taylor-jones** [kristof0425/react-with-breakpoints#30]
Hey there,
First off, this is a really helpful project. I'm pretty new to React, and after looking at some of the markup from the AirBnb site, I was a little bummed to learn that the ShowAt/HideAt feature wasn't built in to React, so I think it's awesome that you've created an open source replica.

Also, I noticed that they have an additional xlarge breakpoint at 1440px that isn't currently included in this project. I've forked and included it to match the nature of your existing code (as best I can tell). Whether you decide to include it or not, I'll still be using your handy project.

**Comment by kristof0425** [comment]
Hey @taylor-jones! 👋 

Thanks for using my module! You have eyes like a hawk! 😉 I also noticed that Airbnb included a new breakpoint, I just didn't have the time to work on it...
So thank you for submitting the pull request, I'm going to include in the package! 👍 

I'll extend your PR a bit if you don't mind. I'll just update the docs as well.
