### ISSUE TITLE
largeAndBelow not working for medium and small

### ISSUE THREAD

**Issue by spietrek** [kristof0425/react-with-breakpoints#35]
In useBreakpoint.ts, small and medium need "largeAndBelow" added. Currently, if you use "largeAndBelow", HideAt will disappear below 1024; however, the component will show back up when the size is 768 or below.

**Comment by kristof0425** [comment]
You are right, I'll investigate the issue more, write a test case for it and release a patch. 👍 Thank you, @spietrek for spotting the issue! 🙇

**Comment by kristof0425** [comment]
The fix is released in `v4.0.1`. 🙂

**Comment by spietrek** [comment]
THANK YOU!!!!
