### ISSUE TITLE
Module not found: Can't resolve 'react-with-breakpoints' Error

### ISSUE THREAD

**Issue by kandelynscott** [kristof0425/react-with-breakpoints#36]
To resolve, I had to change my import to reference the min.js file after updating to 4.0.1 
`import { BreakpointsProvider } from "react-with-breakpoints/dist/react-with-breakpoints.min.js";`
instead of: 
`import { BreakpointsProvider } from "react-with-breakpoints";`

Rolling back to 4.0.0 resolved this too. Briefly comparing the two versions revealed a difference in the file naming where 4.0.0 had the `react-with-breakpoints.umd.js` & `react-with-breakpoints.es5.js` and 4.0.1 had `react-with-breakpoints.min.js` & `react-with-breakpoints.js`

A fix would be much appreciated.

**Comment by kristof0425** [comment]
Thanks for noticing this one, @kandelynscott! I’ll take a look into it!

**Comment by kristof0425** [comment]
All right, `v4.0.2` seems to solve the issue, so I'm closing this. Let me know if you run into anything!
Thanks again!
