### ISSUE TITLE
[Feature Request] onBreakpointChange Event?

### ISSUE THREAD

**Issue by blacksmoke26** [kristof0425/react-with-breakpoints#37]
How to fire an event when breakpoint changes?

Can you implement something like>
```js
// Media query breakpoints
const breakpoints = {
  small: 468,
  medium: 768,
  large: 1024,
  xlarge: Infinity,
};
```

```js
<BreakpointsProvider
  breakpoints={breakpoints}
  onBreakpointChange={( breakpoint ) => {
     // Logic here
  }}>
    {/* ... */}
</BreakpointsProvider>
```

**Comment by darovic** [comment]
Ideally, a change in the breakpoint will cause a change in the state, and react will re-render the virtual DOM and update the DOM with the required changes. Any logic that needs to fire at specific breakpoints can form part of your render logic and will run as needed.

**Comment by kristof0425** [comment]
Sorry for answering this late, @blacksmoke26!

I'm planning to release an update, where I'm going to export the `Context` used by the `BreakpointsProvider`, so you'll be able to implement consumers on your own.

Would that work for you? Please let me know your use-case if it wouldn't!

I can add the `onBreakpointChange` prop easily as well, of course.

**Comment by blacksmoke26** [comment]
Oh thank you :1st_place_medal:
